name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker images
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./docker-compose.yml
        push: true
        registry: docker.io
        username: ${{ secrets.DOCKER_IMAGE_USERNAME }}
        password: ${{ secrets.DOCKER_IMAGE_PASSWORD}}
        tags: |
          docker.io/ama1120/client:local
          docker.io/ama1120/dashboard:local
          docker.io/ama1120/server:local


    # - name: Build and push Docker images
    #   uses: mr-smithers-excellent/docker-build-push@v4
    #   with:
    #     image: ama1120/restaurant-ordering-system
    #     registry: docker.io
    #     dockerfile: ./docker-compose.yml
    #     username: ${{ secrets.DOCKER_IMAGE_USERNAME }}
    #     password: ${{ secrets.DOCKER_IMAGE_PASSWORD}}
