name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.16.1"  

      - name: Dependecies - Dashboard
        run: |
            npm install
        env: 
          CI: ""
        working-directory: ./dashboard

      - name: Build - Dashboard
        run: |
            npm run build
        working-directory: ./dashboard

      - name: Dependecies - client
        run: |
            npm install
        env:
          CI: ""
        working-directory: ./client

      - name: Build - client
        run: |
            npm run build
        working-directory: ./client

      - name: Dependecies - server
        run: |
            npm install
        working-directory: ./server
      
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_IMAGE_PASSWORD }} | docker login -u ${{ secrets.DOCKER_IMAGE_USERNAME }} --password-stdin

      - name: Build and Push - Dashboard
        run: |
            docker-compose build

            docker tag dashboard:local ${{ secrets.DOCKER_IMAGE_USERNAME }}/restaurant-ordering-system:dashboard
            docker tag client:local ${{ secrets.DOCKER_IMAGE_USERNAME }}/restaurant-ordering-system:client
            docker tag server:local ${{ secrets.DOCKER_IMAGE_USERNAME }}/restaurant-ordering-system:server
          
            docker push ${{ secrets.DOCKER_IMAGE_USERNAME }}/restaurant-ordering-system:dashboard
            docker push ${{ secrets.DOCKER_IMAGE_USERNAME }}/restaurant-ordering-system:client
            docker push ${{ secrets.DOCKER_IMAGE_USERNAME }}/restaurant-ordering-system:server

            
      


      

